### ISSUE TITLE
Bugfix - NullPointer on PrimeReference

### ISSUE THREAD

**Issue by MukendiMputu** [MukendiMputu/UserDoc#1]
### NullPointerException while Generating Cinco Product
The Exception occurs when importing the model for the prime reference like so:
    
    import "platform:/resource/info.scce.cinco.product.userdoc/src-gen/info/scce/cinco/product/userdoc/mglid/userdoc/impl/userdoc.ecore" as UserDocTool

and then:
    
    node DocNode{
	    style docNode("${mgl.modelName}")
	    prime UserDocTool.UserDocGraphModel as mgl
	    incomingEdges (*[1,*])
	    outgoingEdges ({Edge,LabeledEdge}[1,*])
    }

#### Task failed:
	UserDoc.mgl: Generating Graphiti editor...

#### Generation of UserDoc.mgl failed
	Error executing 'de.jabc.cinco.meta.core.ge.style.generator.newgraphitigenerator': java.lang.NullPointerException
	java.lang.NullPointerException

        java.lang.RuntimeException: Generation of UserDoc.mgl failed
	        at de.jabc.cinco.meta.core.ui.handlers.CincoProductGenerationHandler.execute(CincoProductGenerationHandler.java:601)
	        at de.jabc.cinco.meta.core.ui.handlers.CincoProductGenerationHandler.generateGraphitiEditor(CincoProductGenerationHandler.java:394)
	        at de.jabc.cinco.meta.core.ui.handlers.CincoProductGenerationHandler.lambda$10(CincoProductGenerationHandler.java:188)
	        at de.jabc.cinco.meta.core.ui.handlers.CincoProductGenerationHandler.lambda$6(CincoProductGenerationHandler.java:200)
		at de.jabc.cinco.meta.core.utils.job.Workload.lambda$8(Workload.java:302)
		at de.jabc.cinco.meta.core.utils.job.Task.lambda$0(Task.java:14)
		at de.jabc.cinco.meta.core.utils.job.Task.run(Task.java:31)
		at de.jabc.cinco.meta.core.utils.job.Workload.lambda$20(Workload.java:425)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at de.jabc.cinco.meta.core.utils.job.Workload.perform(Workload.java:418)
		at de.jabc.cinco.meta.core.utils.job.CompoundJob.perform(CompoundJob.java:446)
		at de.jabc.cinco.meta.core.utils.job.CompoundJob.lambda$9(CompoundJob.java:439)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at de.jabc.cinco.meta.core.utils.job.CompoundJob.run(CompoundJob.java:435)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	    Caused by: org.eclipse.core.commands.ExecutionException: Error executing 'de.jabc.cinco.meta.core.ge.style.generator.newgraphitigenerator': java.lang.NullPointerException
		at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
		at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
		at de.jabc.cinco.meta.core.ui.handlers.CincoProductGenerationHandler.execute(CincoProductGenerationHandler.java:597)
		... 14 more
	Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
		at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
		at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
		at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
		at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
		at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
		... 16 more
	Caused by: java.lang.NullPointerException
		at de.jabc.cinco.meta.core.utils.generator.GeneratorUtils._nsURI(GeneratorUtils.java:1534)
		at de.jabc.cinco.meta.core.utils.generator.GeneratorUtils.nsURI(GeneratorUtils.java:2077)
		at de.jabc.cinco.meta.core.ge.style.generator.templates.FeatureProviderTmpl.generateFeatureProvider(FeatureProviderTmpl.java:294)
		at de.jabc.cinco.meta.core.ge.style.generator.main.GraphitiGeneratorMain.doGenerate(GraphitiGeneratorMain.java:180)
		at de.jabc.cinco.meta.core.ge.style.generator.action.NewGraphitiCodeGenerator$3.apply(NewGraphitiCodeGenerator.java:120)
		at de.jabc.cinco.meta.core.ge.style.generator.action.NewGraphitiCodeGenerator$3.apply(NewGraphitiCodeGenerator.java:1)
		at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:140)
		at de.jabc.cinco.meta.core.ge.style.generator.action.NewGraphitiCodeGenerator.execute(NewGraphitiCodeGenerator.java:123)
		at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
		at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
		at jdk.internal.reflect.GeneratedMethodAccessor269.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
		... 20 more

**Comment by MukendiMputu** [comment]
PrimeReference to another ecore model is not needed.
